-- 修复启动脚本的端口占用处理逻辑
-- 添加强制停止占用端口进程的功能

UPDATE t_ops_app 
SET start_script = CONCAT(
    '#!/bin/bash\n',
    '# Spring Boot 应用启动脚本（带进程验证）\n',
    '\n',
    'APP_NAME="calltask-1.3.1_20260301103333A001"\n',
    'APP_JAR="calltask-1.3.1_20260301103333A001.jar"\n',
    'APP_HOME="/home"\n',
    'LOG_DIR="${APP_HOME}/logs"\n',
    'PID_FILE="${APP_HOME}/${APP_NAME}.pid"\n',
    'PORT=8030\n',
    '\n',
    '# 启用详细输出\n',
    'set -x\n',
    'exec 2>&1\n',
    '\n',
    'echo "[INFO] ========== 开始启动应用 =========="\n',
    'echo "[INFO] 应用名称: ${APP_NAME}"\n',
    'echo "[INFO] JAR 文件: ${APP_JAR}"\n',
    'echo "[INFO] 应用路径: ${APP_HOME}"\n',
    'echo "[INFO] 当前时间: $(date +%Y-%m-%d\\\\ %H:%M:%S)"\n',
    '\n',
    '# 创建日志目录\n',
    'mkdir -p ${LOG_DIR}\n',
    'echo "[INFO] 日志目录: ${LOG_DIR}"\n',
    '\n',
    '# 切换到应用目录\n',
    'cd ${APP_HOME}\n',
    'echo "[INFO] 当前目录: $(pwd)"\n',
    '\n',
    '# 检查 JAR 文件\n',
    'if [ ! -f "${APP_JAR}" ]; then\n',
    '    echo "[ERROR] JAR 文件不存在: ${APP_HOME}/${APP_JAR}"\n',
    '    echo "[ERROR] 目录内容:"\n',
    '    ls -lh ${APP_HOME}\n',
    '    exit 1\n',
    'fi\n',
    'echo "[INFO] JAR 文件存在: ${APP_JAR}"\n',
    '\n',
    '# 检查并停止占用端口的进程\n',
    'echo "[INFO] 检查端口 ${PORT} 是否被占用..."\n',
    'PORT_PID=$(lsof -ti:${PORT} 2>/dev/null || netstat -tulnp 2>/dev/null | grep ":${PORT} " | awk '\''{print $7}'\'' | cut -d/ -f1 | head -1)\n',
    'if [ ! -z "${PORT_PID}" ]; then\n',
    '    echo "[WARN] 端口 ${PORT} 已被进程 ${PORT_PID} 占用"\n',
    '    echo "[INFO] 停止占用端口的进程..."\n',
    '    kill ${PORT_PID} 2>/dev/null || true\n',
    '    sleep 2\n',
    '    if ps -p ${PORT_PID} 1>/dev/null 2>&1; then\n',
    '        echo "[WARN] 强制停止进程 ${PORT_PID}"\n',
    '        kill -9 ${PORT_PID} 2>/dev/null || true\n',
    '        sleep 1\n',
    '    fi\n',
    '    echo "[SUCCESS] 已释放端口 ${PORT}"\n',
    'else\n',
    '    echo "[INFO] 端口 ${PORT} 未被占用"\n',
    'fi\n',
    '\n',
    '# 停止旧进程（通过 PID 文件）\n',
    'if [ -f ${PID_FILE} ]; then\n',
    '    OLD_PID=$(cat ${PID_FILE})\n',
    '    echo "[INFO] 发现旧进程 PID: ${OLD_PID}"\n',
    '    if ps -p ${OLD_PID} 1>/dev/null 2>&1; then\n',
    '        echo "[INFO] 停止旧进程..."\n',
    '        kill ${OLD_PID}\n',
    '        sleep 3\n',
    '        if ps -p ${OLD_PID} 1>/dev/null 2>&1; then\n',
    '            echo "[WARN] 强制停止旧进程"\n',
    '            kill -9 ${OLD_PID}\n',
    '            sleep 1\n',
    '        fi\n',
    '        echo "[SUCCESS] 旧进程已停止"\n',
    '    else\n',
    '        echo "[INFO] 旧进程已不存在"\n',
    '    fi\n',
    '    rm -f ${PID_FILE}\n',
    'fi\n',
    '\n',
    '# 启动应用\n',
    'echo "[INFO] 启动应用..."\n',
    '# 查找 Java 路径\n',
    'JAVA_CMD=$(which java 2>/dev/null || echo "/usr/bin/java")\n',
    'if [ ! -x "${JAVA_CMD}" ]; then\n',
    '    # 尝试常见的 Java 安装路径\n',
    '    for java_path in /usr/bin/java /usr/local/bin/java /opt/java/bin/java; do\n',
    '        if [ -x "${java_path}" ]; then\n',
    '            JAVA_CMD="${java_path}"\n',
    '            break\n',
    '        fi\n',
    '    done\n',
    'fi\n',
    'echo "[INFO] Java 路径: ${JAVA_CMD}"\n',
    '${JAVA_CMD} -version 2>&1 | head -n 1\n',
    '\n',
    'nohup ${JAVA_CMD} -Xms512m -Xmx1024m \\\\\n',
    '    -XX:+UseG1GC \\\\\n',
    '    -XX:+HeapDumpOnOutOfMemoryError \\\\\n',
    '    -XX:HeapDumpPath=${LOG_DIR}/heap_dump.hprof \\\\\n',
    '    -jar ${APP_JAR} --server.port=8030 \\\\\n',
    '    1>${LOG_DIR}/app.log 2>&1 &\n',
    '\n',
    'NEW_PID=$!\n',
    'echo ${NEW_PID} 1>${PID_FILE}\n',
    'echo "[INFO] 应用已后台启动，PID: ${NEW_PID}"\n',
    '\n',
    '# 等待 2 秒，让应用初始化\n',
    'sleep 2\n',
    '\n',
    '# 第一次检查：进程是否还存活\n',
    'if ! ps -p ${NEW_PID} 1>/dev/null 2>&1; then\n',
    '    echo "[ERROR] 应用进程已退出（启动失败）"\n',
    '    echo "[ERROR] 最后 50 行日志:"\n',
    '    tail -n 50 ${LOG_DIR}/app.log\n',
    '    rm -f ${PID_FILE}\n',
    '    exit 1\n',
    'fi\n',
    'echo "[INFO] 初步检查通过，进程仍在运行"\n',
    '\n',
    '# 持续检查 15 秒\n',
    'echo "[INFO] 开始 15 秒稳定性检查..."\n',
    'for i in {1..15}; do\n',
    '    echo "[INFO] 检查进度: ${i}/15 秒"\n',
    '    \n',
    '    if ! ps -p ${NEW_PID} 1>/dev/null 2>&1; then\n',
    '        echo "[ERROR] 应用进程在第 ${i} 秒时退出"\n',
    '        echo "[ERROR] 最后 50 行日志:"\n',
    '        tail -n 50 ${LOG_DIR}/app.log\n',
    '        rm -f ${PID_FILE}\n',
    '        exit 1\n',
    '    fi\n',
    '    \n',
    '    if [ $((i % 5)) -eq 0 ]; then\n',
    '        echo "[INFO] 应用日志最后 5 行:"\n',
    '        tail -n 5 ${LOG_DIR}/app.log | sed "s/^/  /"\n',
    '    fi\n',
    '    \n',
    '    sleep 1\n',
    'done\n',
    '\n',
    '# 最终验证\n',
    'echo "[INFO] ========== 执行最终验证 =========="\n',
    '\n',
    'if ! ps -p ${NEW_PID} 1>/dev/null 2>&1; then\n',
    '    echo "[ERROR] 最终检查失败：进程不存在"\n',
    '    echo "[ERROR] 完整日志:"\n',
    '    cat ${LOG_DIR}/app.log\n',
    '    rm -f ${PID_FILE}\n',
    '    exit 1\n',
    'fi\n',
    'echo "[SUCCESS] 进程存活检查通过"\n',
    '\n',
    'sleep 2\n',
    'if netstat -tuln | grep -q ":${PORT} "; then\n',
    '    echo "[SUCCESS] 端口 ${PORT} 监听检查通过"\n',
    'else\n',
    '    echo "[WARN] 端口 ${PORT} 未监听，应用可能还在启动中"\n',
    'fi\n',
    '\n',
    'echo "[INFO] 进程详细信息:"\n',
    'ps -p ${NEW_PID} -o pid,ppid,cmd,%cpu,%mem,etime | sed "s/^/  /"\n',
    '\n',
    'echo "[INFO] 应用日志最后 20 行:"\n',
    'tail -n 20 ${LOG_DIR}/app.log | sed "s/^/  /"\n',
    '\n',
    'echo "[SUCCESS] ========== 应用启动成功 =========="\n',
    'echo "[INFO] PID: ${NEW_PID}"\n',
    'echo "[INFO] 端口: ${PORT}"\n',
    'echo "[INFO] 日志文件: ${LOG_DIR}/app.log"\n',
    'echo "[INFO] PID 文件: ${PID_FILE}"\n'
)
WHERE app_id = 100;
